// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj92rfUAxNFkf2l9cWMm8fwA5SVk6vUa8',
    appId: '1:165826392337:web:67158812ab517ce5a1dcb0',
    messagingSenderId: '165826392337',
    projectId: 'kurs-web-demo',
    authDomain: 'kurs-web-demo.firebaseapp.com',
    storageBucket: 'kurs-web-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgHuL44jw-TKW4yB97ckVdMs_XGvyl38w',
    appId: '1:165826392337:android:2eed2b99ff831bada1dcb0',
    messagingSenderId: '165826392337',
    projectId: 'kurs-web-demo',
    storageBucket: 'kurs-web-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHI56Yy6WptW75MEDV2bqt_ekOBVx29Y',
    appId: '1:165826392337:ios:f5d03711aeae936ba1dcb0',
    messagingSenderId: '165826392337',
    projectId: 'kurs-web-demo',
    storageBucket: 'kurs-web-demo.appspot.com',
    iosClientId: '165826392337-epn73tnstmlkhm4sk4dan37725vutq6a.apps.googleusercontent.com',
    iosBundleId: 'com.kursdemo.kursdemo',
  );
}
